
services:
  app:
    build: .
    container_name: expense-tracker-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - expense-net

networks:
  expense-net:
